# Generated by Django 3.1.3 on 2021-01-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_app', '0002_post_created_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_data',
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
