# Generated by Django 3.1.4 on 2021-03-30 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas_app', '0008_auto_20210323_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prova',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
