# Generated by Django 3.1.4 on 2021-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_app', '0010_auto_20210412_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='data',
            field=models.DateField(),
        ),
    ]
