# Generated by Django 3.1.4 on 2021-04-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_app', '0011_auto_20210412_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='data',
        ),
    ]
