# Generated by Django 3.1.4 on 2021-04-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas_app', '0014_auto_20210415_1747'),
    ]

    operations = [
        
    ]
